-- Production tenant boundary. Enable REQUIRE_AUTH=true before enabling these policies.
alter table if exists public.user_data enable row level security;
drop policy if exists "user_data_owner" on public.user_data;
create policy "user_data_owner" on public.user_data
  for all using (auth.uid()::text = user_id) with check (auth.uid()::text = user_id);

create table if not exists public.recommendation_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  trace_id text,
  request jsonb not null default '{}'::jsonb,
  recommendations jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.recommendation_history enable row level security;
drop policy if exists "recommendation_history_owner" on public.recommendation_history;
create policy "recommendation_history_owner" on public.recommendation_history
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create table if not exists public.notification_deliveries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content_id bigint not null,
  episode_id bigint not null,
  status text not null check (status in ('sent', 'failed')),
  provider_message_id text,
  created_at timestamptz not null default now(),
  unique (user_id, content_id, episode_id)
);
alter table public.notification_deliveries enable row level security;
drop policy if exists "notification_deliveries_owner" on public.notification_deliveries;
create policy "notification_deliveries_owner" on public.notification_deliveries
  for select using (auth.uid() = user_id);

-- Service-role writes remain server-side; clients never receive the service key.
